version: '3.8'
services:
  redis:
    image: redis:7.2-alpine3.18
    ports:
      - '6379:6379'
  boltzmann-0:
    image: ncorp/boltzmann:latest
    ports:
      - '8081:8080'
    environment:
      BOLTZMANN_REDIS_URL: redis://@redis:6379/0?dial_timeout=3&read_timeout=6s&max_retries=2
  boltzmann-1:
    image: ncorp/boltzmann:latest
    ports:
      - '8082:8080'
    environment:
      BOLTZMANN_REDIS_URL: redis://@redis:6379/0?dial_timeout=3&read_timeout=6s&max_retries=2
  boltzmann-2:
    image: ncorp/boltzmann:latest
    ports:
      - '8083:8080'
    environment:
      BOLTZMANN_REDIS_URL: redis://@redis:6379/0?dial_timeout=3&read_timeout=6s&max_retries=2